ourmy_project/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'ourmy_app.views.index', name='home'),
    url(r'^connect$', 'ourmy_app.views.connect', name='connect'),
    url(r'^test_bootstrap/', include('test_bootstrap.urls')),
    # url(r'^ourmy/', include('ourmy.foo.urls')),

    url(r'^campaign/(?P<campaign_id>\d{0,6})/$', 'ourmy_app.views.campaign', name='campaign'),
    url(r'^create_campaign$', 'ourmy_app.views.create_campaign', name='create_campaign'),
    url(r'^edit_campaign/(?P<campaign_id>\d{0,6})/$', 'ourmy_app.views.create_campaign', name='edit_campaign'),
    url(r'^create_prize/(?P<campaign_id>\d{0,6})/$', 'ourmy_app.views.create_prize', name='create_prize'),
    url(r'^edit_prize/(?P<prize_id>\d{0,6})/$', 'ourmy_app.views.create_prize', name='edit_prize'),

    # url(r'^sharing/', include("sharing.urls", namespace="sharing")),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^login/$', 'ourmy_app.views.campaign', name='login'),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
	# url("^$", direct_to_template, {"template": "index.html"}, name="home"),
    url(r'', include('singly.urls')),
)

# if not settings.DEBUG:
urlpatterns += patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

singly/urls.py
from django.conf.urls import patterns, url
urlpatterns = patterns('singly.views',
    url(r'^authenticate/(?P<service>[a-z]+)/$', 'authenticate_redirect',
        name='authenticate_redirect'),
    url(r'^authorize/callback/$', 'authorize_callback',
        name='authorize_callback')
)

ourmy_app/models.py
import datetime
import os

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils.timezone import utc

from singly.models import SinglyProfile

    
class UserProfile(SinglyProfile):
    singly_profile = models.ForeignKey(SinglyProfile, unique=True, related_name='OurmyUserProfile')
    bio = models.TextField()
    
    def __unicode__(self):
        return self.user.username
    
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


def get_campaign_logo_path(instance, filename):
    return os.path.join('logos', "%d_%s" % (instance.user.id, filename))

def get_prize_logo_path(instance, filename):
    return os.path.join('logos', "%d_%s" % (instance.campaign.user.id, filename))

def tomorrow():
    return datetime.datetime.now().replace(tzinfo=utc) + datetime.timedelta(days=1)


class Campaign(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(blank=True, max_length=100)
    description = models.TextField(blank=True, max_length=250)
    deadline = models.DateTimeField(blank=True, default=tomorrow())
    logo_image = models.FileField(upload_to=get_campaign_logo_path, blank=True, null=True)
    video_url = models.URLField(blank=True)
    api_call = models.CharField(max_length=500, default="sharing.get_actions_for_campaign")

    class Admin:
        list_display = ('',)
        search_fields = ('',)

    def is_past(self):
        return self.deadline <= datetime.datetime.now().replace(tzinfo=utc)

    def days_till_deadline(self):
        delta = self.deadline - datetime.datetime.now().replace(tzinfo=utc)
        return delta.days

    def hours_till_deadline(self):
        delta = self.deadline - datetime.datetime.now().replace(tzinfo=utc)
        return delta.seconds/60/60

    def minutes_till_deadline(self):
        delta = self.deadline - datetime.datetime.now().replace(tzinfo=utc)
        return delta.seconds/60

    def __unicode__(self):
        return self.title


class Prize(models.Model):
    campaign = models.ForeignKey(Campaign)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True, max_length=250)  
    logo_image = models.FileField(upload_to=get_prize_logo_path, blank=True, null=True)
    video_url = models.URLField(blank=True)
    dollar_value = models.DecimalField(max_digits=6, decimal_places=2, default=10)
    points_value = models.IntegerField(default=100)
    how_many = models.IntegerField(default=1)
    place = models.IntegerField(default=1)
    chance = models.NullBooleanField(default=False)

    def __unicode__(self):
        return self.title + ' for ' + self.campaign.title


class CampaignUser(models.Model):
    campaign = models.ForeignKey(Campaign)
    user = models.ForeignKey(User)
    last_checked = models.DateTimeField(default=datetime.datetime.utcnow().replace(tzinfo=utc))
    points_at_deadline = models.IntegerField(default=0)

    def __unicode__(self):
        return self.campaign.title + ', ' + self.user.last_name



class Action(models.Model):
    campaign = models.ForeignKey(Campaign)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    logo_image = models.FileField(upload_to=get_prize_logo_path, blank=True, null=True)
    video_url = models.URLField(blank=True)
    points = models.IntegerField(default=1)
    start_at = models.DateTimeField(blank=True, default=datetime.datetime.utcnow().replace(tzinfo=utc))
    end_at = models.DateTimeField(blank=True, default=datetime.datetime.utcnow().replace(tzinfo=utc))
    api_call = models.CharField(max_length=500)
    last_checked = models.DateTimeField(default=datetime.datetime.utcnow().replace(tzinfo=utc))

    def __unicode__(self):
        return self.campaign.title + ': ' + self.title


class UserAction(models.Model):
    user = models.ForeignKey(User)
    action = models.ForeignKey(Action)
    # last_checked = models.DateTimeField(auto_now_add=True)  # TODO check that auto now add does what I want...

    def __unicode__(self):
        return self.user.username + ' on ' + self.action.title

ourmy_app/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from ourmy_app.models import Campaign, Action, CampaignUser, UserAction, Prize
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.sites.models import get_current_site
from django.template import loader
import datetime
import simplejson
from singly.singly import Singly
from urllib import urlencode
from ourmy_project.settings import SINGLY_CLIENT_ID, SINGLY_CLIENT_SECRET, SINGLY_REDIRECT_URI
from django.conf import settings
from django.core import serializers
from django.conf import settings
import bitly_api

from django import forms
from ourmy_app.forms import CampaignForm, PrizeForm
from django.utils.functional import LazyObject
import sharing
from sharing.models import SharingCampaign, SharingCampaignUser, SharingAction, SharingUserAction
from annoying.functions import get_object_or_None


def index(request):
    current_campaign_list = Campaign.objects.filter(deadline__gt=datetime.datetime.now)
    # this is only a first-time setup thing (because we have no login)
    if len(Campaign.objects.all()) == 0:
        if request.user.is_authenticated():
            user = request.user
            campaign = Campaign(title="deleteme", user=user)
            campaign.save()
            sharing_campaign = SharingCampaign(campaign=campaign)
            sharing_campaign.save()
            fb_action = Action(campaign=campaign, title="facebook", api_call="sharing.get_facebook_post_actions_for_user")
            fb_action.save()
            tw_action = Action(campaign=campaign, title="twitter", api_call="sharing.get_twitter_post_actions_for_user")
            tw_action.save()
            click_action = Action(campaign=campaign, title="click", api_call="sharing.get_click_actions_for_user")
            click_action.save()
            fb_sharing_action = SharingAction(action=fb_action, social_network='FB', post_or_click=False)
            fb_sharing_action.save()
            tw_sharing_action = SharingAction(action=tw_action, social_network='TW', post_or_click=False)
            tw_sharing_action.save()
            click_sharing_action = SharingAction(action=click_action, social_network='FB', post_or_click=True)
            click_sharing_action.save()
            current_campaign_list = Campaign.objects.filter(deadline__gt=datetime.datetime.now)

    return render_to_response('index.html', 
        {'campaign_list':current_campaign_list},
        context_instance=RequestContext(request))

@login_required
def create_campaign(request, campaign_id=None):
    campaign=None
    campaigns = []
    campaigns = Campaign.objects.filter(user=request.user)
    if campaigns == []:
        return HttpResponseRedirect(reverse('index'))
    is_saved = False

    if request.method == 'POST':
        if campaign_id is not None:
            campaign = get_object_or_404(Campaign, pk=campaign_id)
            is_saved = True

        form = CampaignForm(request.POST, request.FILES, instance=campaign)
        if form.is_valid():
            form.instance.user = request.user
            # ZT001:  this is temporary -- when we can promote non-video urls we'll put it back into the form.
            form.instance.video_url = request.POST['long_url']
            form.save()

            sharing_campaign, created = SharingCampaign.objects.get_or_create(campaign=form.instance)
            sharing_campaign.long_url = request.POST['long_url']
            sharing_campaign.post_text = request.POST['post_text']
            sharing_campaign.save()
            
            # now we create the actions and sharing actions.  One post for each service, one click.
            services = SharingAction.SOCIAL_NETWORK_CHOICES
            for service in services:
                post_action, created = Action.objects.get_or_create(campaign=form.instance, title=service[1], points=10,
                                    api_call="sharing.get_%s_post_actions_for_user" % service[1])
                post_action.save()
                sharing_post_action, created = SharingAction.objects.get_or_create(action=post_action, social_network=service[0], post_or_click=False)
                sharing_post_action.save()
            click_action, created = Action.objects.get_or_create(campaign=form.instance, title="click",
                                  api_call="sharing.get_click_actions_for_user")
            click_action.save()
            sharing_click_action, created = SharingAction.objects.get_or_create(action=click_action, social_network=service[0], post_or_click=True)
            sharing_click_action.save()
            # return HttpResponseRedirect("/")
            url = reverse('edit_campaign', kwargs={'campaign_id':form.instance.id})
            return HttpResponseRedirect(url)
        else:
            # print "printing form errors:"
            # print form.errors
            pass
    else:
        if campaign_id is not None:
            campaign = get_object_or_404(Campaign, pk=campaign_id)
            is_saved = True
            sharing_campaign = SharingCampaign.objects.get(campaign=campaign)
            form = CampaignForm(instance=campaign, initial={'long_url':sharing_campaign.long_url, 'post_text':sharing_campaign.post_text})
        else:
            form = CampaignForm()

    return render_to_response("create_campaign.html", {'form':form, 'campaigns':campaigns, 'this_campaign':campaign, 'is_saved':is_saved},
        context_instance=RequestContext(request))

@login_required
def create_prize(request, prize_id=None, campaign_id=None):
    instance = None
    prizes_for_campaign = None
    campaign = None
    is_saved = False
    # we will either get a campaign_id (create) or a pitch_id (edit)
    # if there's a campaign id, this is a new prize.  Get the campaign, create & save the prize
    if campaign_id:
        campaign = get_object_or_404(Campaign, pk=campaign_id)
        prizes_for_campaign = Prize.objects.filter(campaign=campaign)
        instance = Prize(campaign=campaign)
    elif prize_id:
        instance = get_object_or_404(Prize, pk=prize_id)
        campaign = instance.campaign
        prizes_for_campaign = Prize.objects.filter(campaign=campaign)
        is_saved = True
    if request.method == 'POST':
        instance = get_object_or_None(Prize, campaign=campaign, title=request.POST['title'])
        if instance is None:
            instance = Prize(campaign=campaign)
        form = PrizeForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
        instance = Prize(campaign=campaign)
        form = PrizeForm(instance=instance)
    else:
        form = PrizeForm(instance=instance)
    return render_to_response("create_prize.html", {'form':form, 'all_prizes':prizes_for_campaign, 'campaign':campaign, 'is_saved':is_saved},
        context_instance=RequestContext(request))



def campaign(request, campaign_id):
    campaign = get_object_or_404(Campaign, pk=campaign_id)
    sharing_campaign_user = None
    profiles = None         # profiles is a list of the social networks this user is logged in to.
    posted_to = None        # has the user just posted?  We thank them if so.
    this_users_points = 0   # we use this to calculate how many points they need to win certain prizes

    services = SharingAction.SOCIAL_NETWORK_CHOICES
    actions = SharingAction.objects.filter(action__campaign=campaign, post_or_click=False)

    ##################
    # if they post to social networks:
    ##################
    # TODO: clean up the Sharing module and this stuff -- sharing should not keep accessing ourmy_app models
    if request.method == 'POST': 

        # get the list of social networks the user posted to from the checkboxes
        social_networks_list = request.POST.getlist('social-networks')
        posted_to = ",".join(social_networks_list)        
        body = request.POST['body']
        url = request.POST['url']
        # posting happens in the sharing module
        sharing.post_to_social_networks(user=request.user, social_networks_list=social_networks_list, body=body, url=url, campaign=campaign)


    ###############
    # Leaderboard #
    ###############
    campaign_users = CampaignUser.objects.filter(campaign=campaign)

    for campaign_user in campaign_users:
        campaign_user.points = 0
        # get all the actions this user has done by pinging the api call
        # TODO: should we delete any user_actions that are not returned by this call?
        words = campaign.api_call.split(".")
        module = __import__(words[0])
        funct = getattr(module, words[1])
        list_of_actions_ids = funct(campaign)
        # for each element, get or create a new UserAction.
        for action_id in list_of_actions_ids:
            action = get_object_or_None(Action, api_call=action_id, campaign=campaign)
            # create any user actions that don't exist
            if action:
                user_action, created = UserAction.objects.get_or_create(user=campaign_user.user, action=action)
                user_action.save()

        user_actions = UserAction.objects.filter(user=campaign_user.user)

        for user_action in user_actions:
            # call the api for this action.  This returns how many of these actions this user did.
            points_call = user_action.action.api_call
            words = points_call.split(".")
            module = __import__(words[0])
            funct = getattr(module, words[1])
            campaign_user.points += user_action.action.points * funct(campaign_user.user, campaign)
            # if the deadline has passed and the campaign user does not have a points_at_deadline, save this point value
            if campaign.is_past and campaign_user.points_at_deadline == 0:

ourmy_app/templates/campaign.html
{% extends "base.html" %}

{% block content %}

{% load ourmy_app_extras %}

<div class="campaign-media">
	<iframe width="280" height="210" src="http://www.youtube.com/embed/{{ youtube_id }}" frameborder="0" allowfullscreen></iframe>
</div>	

<div class="sharing-center">
<form class="form-vertical" action="" method="post">
{% csrf_token %}
  <fieldset>
    <h2 class="campaign-title">Sharing tools</h2>
    {% if posted_to %}
	    <p>Thanks for posting to {{ posted_to }}!  Post again to collect even more points.</p>
    {% endif %}
	<p>Share this campaign to win unique rewards and support the creator:</p>
	    <ul class="networks">
	    {% for action in actions %}
	        <li>
                {% if action.get_social_network_display in profiles %}
                    <input type="checkbox" value="{{action.get_social_network_display}}" name="social-networks">
					<!-- <span class="check">&#10003; -->
					</span><a class="social-button" href="/authenticate/{{ action.get_social_network_display }}"><img src="{{ STATIC_URL }}img/{{ action.get_social_network_display }}-on.png" title="{{ action.get_social_network_display }}" width="80"/><br />{{ action.action.points }} point{{ action.action.points|pluralize }}</a>
				{% else %}	
					<a class="social-button" href="/authenticate/{{ action.get_social_network_display }}"><img src="{{ STATIC_URL }}img/{{ action.get_social_network_display }}-off.png" title="{{ action.get_social_network_display }}" width="80"/></a>
                {% endif %}
	        </li>
	    {% endfor %}

	    {% if profiles %}
			<div class="helper-text">Check the box of each social network you want to post to. The same message goes to each network you select.  To use different messages, check only one and click SHARE, then check another, change the message, and click SHARE again.</div>
		{% else %}
			<div class="helper-text">Click on the social icons to the left to connect your accounts.  The more accounts you connect, the more points you can earn!</div>
		{% endif %}

	    </ul>
    <div class="control-group">
      <label class="control-label" for="textarea">My message:</label>
      <div class="controls">
        <textarea class="input-xlarge" name="body" id="body" rows="3">{{ sharing_campaign_user.sharing_campaign.post_text }}
        </textarea>
      </div>
    </div>

    <div class="control-group">
	    <label class="control-label" for="input01">This link will be included in your post:</label>
		<div class="controls">

	        <input type="hidden" name="url" class="input-xlarge disabled" id="url" value="{{ sharing_campaign_user.sharable_url }}">
	        <p>{{ sharing_campaign_user.sharable_url }}</p>
	        <p class="help-block">This link has been uniquely generated for you by Ourmy to track your sharing points.</p>
			<div class="form-actions">
	        {% if user.is_authenticated %}
			    <button type="submit" class="btn post-button">SHARE</button>
			{% else %}
				<a href="#" class="btn post-button" rel="popover" data-placement="top" title="Oh no! You're not logged in!" data-content="Before you can share this great campaign log in by clicking either the facebook or twitter button to the left to connect.  Ourmy needs this in order to track your points so you can win rewards.">SHARE</a>
			{% endif %}
			</div>

	    </div>
	</div>

  </fieldset>
</form>
</div>

<div class="leaderboard">
	<div class="banner-header"><h1>Campaign Scoreboard</h1></div>
	<ul class="rankings">
		{% for campaign_user in campaign_users %}
			{% if campaign.is_past %}
				<li class="gamer"><span class="calloutpoint-score"><h2>{{ campaign_user.points_at_deadline }}</h2></span><span class="player">{{ campaign_user.user.first_name }}</span><img class="profile-pic-scoreboard" src="{{ campaign_user.user.get_profile.thumbnail_url }}"></img></li>
			{% else %}
				<li class="gamer"><span class="calloutpoint-score"><h2>{{ campaign_user.points }}</h2></span><span class="player">{{ campaign_user.user.first_name }}</span><img class="profile-pic-scoreboard" src="{{ campaign_user.user.get_profile.thumbnail_url }}"></img></li>
			{% endif %}
		{% endfor %}
	</ul>
</div>

<div class="campaign-dashboard">
	<h2 class="campaign-title">Campaign rewards</h2>
	{% for prize in campaign.prize_set.all %}
		<div class="single-prize">
			<div>
				{% if this_users_points < prize.points_value %}
				<div class="prize-cta"><p>Collect {{ prize.points_value|subtract:this_users_points }} more points to be entered to win!</p></div>
				{% else %} <div class="prize-cta-else"><p>You're in the running for this prize!</p></div>
				{% endif %}
			</div>
			<div class="campaign-prize-title"><p>{{ prize.title }}</p></div>
			{% if prize.logo_image %}
			<img src="{{ MEDIA_URL }}{{ prize.logo_image }}" width="80" /> 
			{% else %}
			<img src="{{ STATIC_URL }}img/ourmy_default_prize_badge.png" width="80" />
			{% endif %}
			<div class="prize-description"><p>{{ prize.description }}</p></div>
		</div>
	{% endfor %}
	<div class="clearfix"></div>
	<div class="campaign-description">
	<h2 class="campaign-title">{{ campaign.title }}<span class="creator">&nbsp; by {{campaign.user.first_name}}&nbsp;{{campaign.user.last_name}}</span></h2> 
	<p>{{ campaign.description }}</p>
	</div>
</div>	

<br></br>



{% for action in campaign.actions %}
	<p>{{ action.social_network }}</p>
	<p>{{ action.text }}</p>
	<p>{{ action.points }}</p>
{% endfor %}

{% endblock content %}

ourmy_app/templates/create_campaign.html
{% extends "base.html" %}

{% block content %}

<h2 class="campaign-title">Create your campaign!<br />
  {% if campaigns %}
    or 
    <select ONCHANGE="location = this.options[this.selectedIndex].value;">
      <option>Edit a different campaign</option>
      {% for campaign in campaigns %}
        <option value="{% url edit_campaign campaign_id=campaign.id %}">{{ campaign.title }}</option>
      {% endfor %}
      {% if is_saved %}
        {% if request.user.is_staff %}
          <option value="{% url create_campaign %}">Add a new campaign</option>
        {% endif %}
      {% endif %}
    </select><h2>
  {% endif %}

<div class="padding">
<form enctype="multipart/form-data" action="" method="POST">
      {% csrf_token %}
      <fieldset>
      {{ form }}
      <div class="actions">
        <input type="submit" class="btn primary btn-offset-top" value="CREATE CAMPAIGN">
      </div>
      </fieldset>
    </form>
</div>

{% if is_saved %}
<div>
<a class="btn primary" href="{% url create_prize campaign_id=this_campaign.id %}">CREATE PRIZES</a>
&nbsp;&nbsp;Create prizes to reward your most loyal friends and fans!
</div>
{% endif %}
{% endblock content %}

ourmy_app/templates/create_prize.html
{% extends "base.html" %}

{% block content %}

<div class="span5">

<a class="btn btn-primary" href="{% url edit_campaign campaign_id=campaign.id %}">< BACK TO CAMPAIGN SETUP</a>
  <h2 class="campaign-title">Create your prize for {{ campaign.title }}<br />
    {% if all_prizes %}
      or 
      <select ONCHANGE="location = this.options[this.selectedIndex].value;">
        <option>Edit a different prize</option>
        {% for prize in all_prizes %}
            <option value="{% url edit_prize prize_id=prize.id %}">{{ prize.title }}</option>
        {% endfor %}
        {% if is_saved %}
            <option value="{% url create_prize campaign_id=campaign.id %}">Add a new prize</option>
        {% endif %}
      </select><h2>
    {% endif %}

  <div class="padding">
  <form enctype="multipart/form-data" action="" method="POST">
        {% csrf_token %}
        <fieldset>
        {{ form }}
        <div class="actions">
          <input type="submit" class="btn primary btn-large" value="SAVE PRIZE">
        </div>
        </fieldset>
      </form>
  </div>
</div>

<div class="span5">
  <h2 class="campaign-title span5-right-title">Prizes so far:</h2>
  {% for prize in all_prizes %}
    <h4>{{ prize.title }}</h4>
    <p>{{ prize.description }}</p>
  {% endfor %}
</div>

{% endblock content %}

ourmy_app/templates/index.html
{% extends "base.html" %}
{% block content %}


<div class="header cover">
    <div class="container">
        <div class="row">
			<div class="tag-holder">
				<h1 class="logline">Share Creativity. Get Rewards. Easy.</h1> 
			</div>
		</div>
	</div>
</div>

<div class="clearfix"></div>

<div class="row">
	<h2 class="page-title">New Campaigns</h2>
</div>

{% for campaign in campaign_list %}
	<div class="container campaign">
		<a href="{% url campaign campaign_id=campaign.id %}">
		<div class="profile-pic"><img src="{{ MEDIA_URL }}{{ campaign.logo_image }}" />
		</a>
		</div>
		<div class="campaign-text">
			<h2 class="campaign-title">{{ campaign.title }} <span class="creator small-creator">&nbsp;by {{campaign.user.first_name}}&nbsp;{{campaign.user.last_name}}</span></h2>		
			<p class="campaign-description">{{ campaign.description }}</p>
			{% if campaign.days_till_deadline >= 1 %}
			<p class="text-warning">&#171;&nbsp;&nbsp;Only {{ campaign.days_till_deadline }} days left to support {{ campaign.title }}!</p>
			{% elif campaign.minutes_till_deadline >= 60 %}
			<p class="text-warning">&#171;&nbsp;&nbsp;Only {{ campaign.hours_till_deadline }} hours left to support {{ campaign.title }}!</p>
			{% else %}
			<p class="text-warning">&#171;&nbsp;&nbsp;Only {{ campaign.minutes_till_deadline }} minutes left to {{ campaign.title }} !</p>
			{% endif %}
		</div>
		<div class="promote-button">
			<a href="{% url campaign campaign_id=campaign.id %}" class="btn btn-large promo-button-layout">SUPPORT THIS PROJECT</a>
		</div>
		<a href="https://twitter.com/share" class="twitter-share-button" data-text="Win rewards for spreading the word about amazing creative projects" data-via="0urmy" data-related="ZoomTilt" data-hashtags="creativearmy">Tweet</a>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
		<p class="prizes-title">Support <strong>{{ campaign.title }}</strong> for a chance to win:</p>
		<div class="prize-placement">
		{{ campaign.prizes }}
		{% for prize in campaign.prize_set.all %}
			<div class="prize-listing">
			{% if prize.logo_image %}
				<img src="{{ MEDIA_URL }}{{ prize.logo_image }}" width="120" height="100%" /> 
			{% else %}
				<img src="{{ STATIC_URL }}img/ourmy_default_prize_badge.png" width="80" height="100%" />
			{% endif %} 
				<div class="prize-tag">{{ prize.title }}, worth ${{ prize.dollar_value }}!</div></div>
		{% endfor %}
		</div>
		</div>

{% endfor %}

{% endblock %}

ourmy_app/templates/login.html
{% extends "base.html" %}

{% block content %}

      <ul class="networks">
      {% for service in services %}
          <li>
                {% if service.lower in profiles %}
                    <span class="check">&#10003;</span><a class="social-button" href="/authenticate/{{ service.lower }}"><img src="{{ STATIC_URL }}img/{{service.lower}}-on.png" title="{{ service }}" width="80"/></a>
        {% else %}  
          <a class="social-button" href="/authenticate/{{ service.lower }}"><img src="{{ STATIC_URL }}img/{{service.lower}}-off.png" title="{{ service }}" width="80"/></a>
                {% endif %}
          </li>
      {% endfor %}
    <p class="helper-text">Click on the social icons to the left to connect your accounts.  The more accounts you connect, the more points you earn!</p>
      </ul>

{% endblock content %}

ourmy_app/templates/post.html
{% extends "base.html" %}

{% block content %}
<h1>Thanks for sharing!</h1>
You've just earned 13 points and unlocked the Top Sharer achievement.
{% endblock %}